CREATE DATABASE numbers
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;
	
	
	

-- Table: public.GUESTS

-- DROP TABLE IF EXISTS public."GUESTS";

CREATE TABLE IF NOT EXISTS public."GUESTS"
(
    "ID_SESSION" uuid NOT NULL,
    "NICKNAME" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "GUESTS_pkey" PRIMARY KEY ("ID_SESSION")
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."GUESTS"
    OWNER to postgres;
	
	



-- Table: public.ROOMS

-- DROP TABLE IF EXISTS public."ROOMS";

CREATE TABLE IF NOT EXISTS public."ROOMS"
(
    "ID" serial NOT NULL,
    "NAME" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "ID_PLAYER_1" uuid,
    "ID_PLAYER_2" uuid,
    CONSTRAINT "ROOMS_pkey" PRIMARY KEY ("ID"),
	CONSTRAINT "ID_PLAYER_1" FOREIGN KEY ("ID_PLAYER_1")
        REFERENCES public."GUESTS" ("ID_SESSION") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
	CONSTRAINT "ID_PLAYER_2" FOREIGN KEY ("ID_PLAYER_2")
        REFERENCES public."GUESTS" ("ID_SESSION") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."ROOMS"
    OWNER to postgres;

	
-- Table: public.GUESS_HISTORY

-- DROP TABLE IF EXISTS public."GUESS_HISTORY";

CREATE TABLE IF NOT EXISTS public."GUESS_HISTORY"
(
    "ID_GUESS_HISTORY" serial NOT NULL,
    "ID_PLAYER" uuid NOT NULL,
    "GUESS_NUMBER" bigint NOT NULL,
    "CORRECT_POSITIONS" integer NOT NULL DEFAULT 0,
    "WRONG_POSITIONS" integer NOT NULL DEFAULT 0,
    "ID_ROOM" bigint,
    CONSTRAINT "GUESS_HISTORY_pkey" PRIMARY KEY ("ID_GUESS_HISTORY"),
    CONSTRAINT "ID_ROOM" FOREIGN KEY ("ID_ROOM")
        REFERENCES public."ROOMS" ("ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
	CONSTRAINT "ID_PLAYER" FOREIGN KEY ("ID_PLAYER")
        REFERENCES public."GUESTS" ("ID_SESSION") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."GUESS_HISTORY"
    OWNER to postgres;